### ISSUE TITLE
缺少依赖   Lack of dependencies

### ISSUE THREAD

**Issue by Physics365** [qiufuyu123/CasioEmuNeo#1]
![image](https://github.com/qiufuyu123/CasioEmuNeo/assets/154725076/7c8e2de5-64af-4d16-bc73-634f1a43805f)
**如图，缺少libgcc_s_seh-1.dll，但是我安装了mingw64
As shown in the image, the libgcc_s_seh-1.dll is missing, but I have mingw64 installed
按下确定后退出
It quits after pressing OK**

**Comment by qiufuyu123** [comment]
我已经更新了release,去release里重下一下

**Comment by Physics365** [comment]
谢谢，解决了
