### ISSUE TITLE
中文语言下，为什么有些中文字依然显示不了？

### ISSUE THREAD

**Issue by bczhc** [qiufuyu123/CasioEmuNeo#12]
比如输入“小端”，“小”字能正常显示，但“端”就不行。
<img width="49" alt="image" src="https://github.com/qiufuyu123/CasioEmuNeo/assets/49330580/42815fb6-fac7-4f2f-aeb6-ace3c5de8676">

使用字体是release里面带的unifont，看了“端”字是在字体里的
<img width="236" alt="image" src="https://github.com/qiufuyu123/CasioEmuNeo/assets/49330580/abfeb60f-b92e-441a-b997-f88a12b96051">

**Comment by qiufuyu123** [comment]
![image](https://github.com/qiufuyu123/CasioEmuNeo/assets/60765480/65cdfc69-cd49-4b25-8cac-10fc78645615)

imgui字体渲染方式的局限性
在这个函数里，我只加载了语言文件里所有用到的字体，需要别的字符请按照imgui加载中文的教程

**Comment by qiufuyu123** [comment]
![image](https://github.com/qiufuyu123/CasioEmuNeo/assets/60765480/74f8f5be-6cf2-4ad3-a8ca-cc410128177e)
k可以参考这个

**Comment by bczhc** [comment]
了解了。
