### ISSUE TITLE
关于字体模糊的问题

### ISSUE THREAD

**Issue by bczhc** [qiufuyu123/CasioEmuNeo#13]
目前这个值`18.0`是写死的。

https://github.com/qiufuyu123/CasioEmuNeo/blob/cb3a93d49768acab21fa8df99ecb954f18ac2709/emulator/Gui/Ui.cpp#L33

在1.0倍缩放下，字体显示如下：
<img alt="image" src="https://github.com/qiufuyu123/CasioEmuNeo/assets/49330580/a8fc045a-6ca9-4ce2-a918-39017cb7bb5c">
但将字体栅格化大小改成36.0，缩放应用0.5，字体就能变清晰（一些些）：
<img alt="image" src="https://github.com/qiufuyu123/CasioEmuNeo/assets/49330580/82c481e3-2773-4a1e-8f4c-7e9eacd2c6b8">
同样地，再加大`size_pixels`值，减小缩放，字体会越来越清晰。

`size_pixels`值是否要改成可配置的？

**Comment by qiufuyu123** [comment]
[这里](https://github.com/qiufuyu123/CasioEmuNeo/commit/b4587631523962874922aaa2d6370aa4707f1b40) 应该修了，这个值改成16,缩放给到0.75即可
参考[这个](https://github.com/Physics365/991CN-X-CW-Decompilation/discussions/18#discussioncomment-9168747)
