### ISSUE TITLE
Windows缩放窗口导致程序崩溃

### ISSUE THREAD

**Issue by Physics365** [qiufuyu123/CasioEmuNeo#22]
Windows缩放窗口导致程序崩。
release版本无此问题，自己编译的有。
和放不放字体无关。

https://github.com/qiufuyu123/CasioEmuNeo/assets/154725076/8b387aac-5a69-4727-92c7-e34a4e59d987

**Comment by Physics365** [comment]
和上次你们调了缩放有关吗

**Comment by qiufuyu123** [comment]
多线程渲染的一些Bug
SDL渲染函数只能放在主函数，不然捕获不到windows下的缩放事件，非常奇怪 🥲 
请拉取最新代码，已经在 commit 58 修复

**Comment by Physics365** [comment]
感谢，已修复
