### ISSUE TITLE
添加中文支持

### ISSUE THREAD

**Issue by Wenti-D** [qiufuyu123/CasioEmuNeo#3]
虽说能来到这里的大伙基本上都认识英语，但这个模拟器的受众必然有一部分人只会中文，不妨考虑添加中文支持？

**Comment by qiufuyu123** [comment]
多语言支持已经在下面的commit中实现，可自行定制语言包
[多语言支持commit](https://github.com/qiufuyu123/CasioEmuNeo/commit/aec589f60d12368b83719e9aebb6b7016306cdf9)
或者直接下载release版本:
[v0.2.0](https://github.com/qiufuyu123/CasioEmuNeo/releases/tag/v0.2.0)

**Comment by Wenti-D** [comment]
## 好！

**但是：**

- 一般问题：
  - 字体是只能一字不差地识别 `font.ttc` 文件名吗？想自定义字体可能会带来难度，毕竟一般的字体以 OTF 与 TTF 居多；
- 自编译版本：
  - 没有提示说要配置自定义字体（`font.ttc` 文件）来显示中文；
- 打包发布版本：
  - 直接双击是无法运行的（如图），必须手动指定路径。
    ![image](https://github.com/qiufuyu123/CasioEmuNeo/assets/73067578/6be016cf-4dfe-4882-b84b-9eb0089c894a)

**其他建议：**

既然用了 ImGui，不妨用用 [Unifont](https://unifoundry.com/unifont/index.html)——支持 Unicode 的免费像素字体，如果不想要像素字体，可以用用[等距更纱黑体](https://github.com/be5invis/Sarasa-Gothic)，微软雅黑似乎不太适合这种场合……

**Comment by qiufuyu123** [comment]
请查看最新release 和 最新commit
已经支持自定义字体加载(默认为unifont)

- 打包时添加config.ini为了方便用户配置（如果不手动创建的话，程序不会自动创建，而是使用默认配置）
- git里面留着主要是方便调试，因为调试的时候路径不太一样

**Comment by Wenti-D** [comment]
# 好！
