### ISSUE TITLE
文件夹位置错误导致程序闪退

### ISSUE THREAD

**Issue by Physics365** [qiufuyu123/CasioEmuNeo#4]
如图，运行后闪退
`D:\Casio反编译\CasioEmuNeo-Mingw-portable-v0.2\release>.\CasioEmuNeo.exe

emulator\Emulator.cpp:278: in void casioemu::Emulator::LoadModelDefition(): LoadModelDefition failed: cannot open E:/projects/CasioEmuX/models/fx991cnx/model.lua: No such file or directory`

**Comment by Physics365** [comment]
![屏幕截图 2024-03-23 215625](https://github.com/qiufuyu123/CasioEmuNeo/assets/154725076/0072aab9-311d-466d-a643-74748806e18d)

**Comment by qiufuyu123** [comment]
已经修复，请查看最新release

**Comment by Physics365** [comment]
只有在E盘里放这个所谓的projects的时候才能正常运行

**Comment by qiufuyu123** [comment]
调试宏忘记删了 eeee

**Comment by Physics365** [comment]
感谢，已修复

**Comment by qiufuyu123** [comment]
ok
