### ISSUE TITLE
关于`models`文件夹的路径

### ISSUE THREAD

**Issue by bczhc** [qiufuyu123/CasioEmuNeo#6]
README中没看到`models`文件夹应该放哪。如果在项目根目录的话（[user202729/CasioEmu](https://github.com/user202729/CasioEmu)是放在根目录的），那README中的运行方式会报路径找不到：

```console
~/open-source/CasioEmuNeo/emulator master !5 ?1 ❯ ls ../models
fx991cnx
~/open-source/CasioEmuNeo/emulator master !5 ?1 ❯ xmake run CasioEmuX ../models/fx991cnx
emulator/Emulator.cpp:278: in void casioemu::Emulator::LoadModelDefition(): LoadModelDefition failed: cannot open ../models/fx991cnx/model.lua: No such file or directory
error: execv(/home/bczhc/open-source/CasioEmuNeo/build/linux/x86_64/release/CasioEmuX ../models/fx991cnx) failed(1)
```

解决办法：
1. 在主程序中用`getcwd`获取工作目录，可以看到工作目录是项目根目录，所以得在`emulator`目录中执行`xmake run CasioEmuX models/fx991cnx`而没有那个`../`。
2. 直接执行编译的二进制文件。

   ```console
   ~/open-source/CasioEmuNeo/emulator master !5 ?1 ❯ ../build/linux/x86_64/release/CasioEmuX ../models/fx991cnx
   ```

如果`models`在项目根目录，是否README应去掉`../`？

**Comment by qiufuyu123** [comment]
是这个样子，如果不生成可执行文件，直接xmake run
需要再casioemu.cpp里创建一个DEBUG的宏，具体看main函数里有关这个宏的判断
![image](https://github.com/qiufuyu123/CasioEmuNeo/assets/60765480/94f4e13f-fda8-40ca-b3d1-bbb7a22c1241)
调试的时候直接打开这个#define DEBUG 就行了

但是在发布release的时候删掉这个宏，这样就能正确找到路径了
(release版本的model就是直接放在根目录的
